### PR TITLE
Finish Getting Started, improve JS

### PR DESCRIPTION
**Pull request by rwjuk**
This PR fleshes out the Getting Started page and adds a link to it from the homepage, and refactors the JS in order to make showing/hiding content based on platform easier.

The Getting Started page should automatically display the relevant content for the user's platform (assuming their browser reports things sensibly). Of course, the user can simply click the relevant button to see the other sections.

See it in action [here](http://serenity.uk.net/openrct2/index.html).

### CODE REVIEW

**Comment by Krutonium** [comment]
Under "Install OpenRCT2", it seems someone added an instruction to most of the lists, but didn't update the step number. For example, under Fedora, the steps go 1, 2, 3, 2.

**Comment by Krutonium** [comment]
Under Arch Linux, you should also mention the `-git` package for those who want the most up to date (Multiplayer Ready) builds.

**Comment by rwjuk** [comment]
@PFCKrutonium Both addressed.

Note: check background scrolling on FF, Win10

**Comment by IntelOrca** [comment]
I think in the Extract to files section, macOS and Linux should be split so the user is not to get confused with the interleaving instructions. And we could implement it by having maybe having a class on each paragraph to say whether it should be shown / hidden for a particular platform so we don't completely duplicate everything.

**Comment by janisozaur** [comment]
1. It could use instructions for Android too, see https://github.com/OpenRCT2/OpenRCT2/wiki/Android
2. The launchpad PPAs are out of date and they should at least come with a big fat warning
3. I am not sure if the ports to other distros are maintained at all. I care about Arch one and it's mostly up-to-date

**Comment by IntelOrca** [comment]
Perhaps for Debian / Ubuntu, we should just link to our own builds.

**Pull request merged**
