### PR TITLE
Added OpenSSL 1.0.2h to OS X libs

### PR DESCRIPTION
**Pull request by LRFLEW**
It's probably best not to merge this here. I made some structural changes to the file, and got rid of the long-obsolete source libraries. This should also be moved to the Dependencies repo. I'll write up how this differs from #17 later, as I'm too tired to do it now.

### CODE REVIEW

**Comment by janisozaur** [comment]
This is now live at https://github.com/OpenRCT2/Dependencies/releases/tag/v8

**Comment by LRFLEW** [comment]
Ok, time to writeup the differences from #17, as well as provide a general guideline for others to be able to make builds. This is fairly non-obvious, so I'd like to look over any future builds to make sure everything looks right.
- The first change is the most obvious, but also the one that doesn't fix any broken builds. Along with not including extra files (the static libraries and `pkgconfig`), I made the binaries 32-bit only. This saves space on downloads of the game, and is just a generally better way of doing it. The main problem is that Homebrew doesn't allow you to build 32-bit only binaries. While there are ways of converting an universal library to a 32-bit library, I find it easier to download the source and build it from there. For most libraries, you can build them as 32-bit by adding `-m32` to the `CFLAGS` and `LDFLAGS` variables. OpenSSL is the exception, where (for 1.0.2 at least), the default is 32-bit only.
- The OpenRCT2 binary is built with compatibility going back to OS X 10.7 (I don't know if it's been tested in that version, but the flags are set so that it will at least try to run). However, any libraries it loads needs to be build with the same version compatibility to allow it to properly load. Homebrew only builds with the compatibility set to the OS X version it was built on, and I'm fairly certain there's no way to change that. When building from source, it usually defaults the same way as Homebrew (with some exceptions). For most libraries, you can add `-mmacosx-version-min=10.7` to `CFLAGS` and `LDFLAGS` variables. OpenSSL doesn't use those variables, so you can just add the `-mmacosx-version-min=10.7` to the call to `./config` to do the same thing.
- The last one is both the most important, and the most subtle. Let's take a build library file called `libSomething.dylib`. Let's assume you built it by configuring with `--prefix=/some/prefix/here/`. Call `otool -L some-lib.dylib`, and you will get something that looks something like this:

```
libSomething.dylib:
    /some/prefix/here/lib/libSomething.2.0.0.dylib (compatibility version 5.0.0, current version 5.0.0)
    /usr/local/opt/otherthing/lib/libOther.6.dylib (compatibility version 19.0.0, current version 19.3.0)
    /usr/lib/libThing.2.dylib (compatibility version 7.0.0, current version 7.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

I'll summarize what this means. The first line is the file as given to otool (this is to handle when you pass it multiple files). The next line is the binary's `id`. This line is generally always the id (with the only exception I've seen being the OpenSSL engine .dylib files). The third line refers to some library installed via Homebrew. If you see a library like this, you should make sure it's included in the orctlibs bundle (for example, SDL2_ttf forces us to include freetype). Let's call these `user dependencies` for now. The next line refers to a system dependency. These do not need to be included in the libs bundle, as they can be assumed to be on the user's system by default. These can also be from a framework, in which case it will start with `/System/Library/Frameworks/`. Lastly, we have the C standard library. There's a similar file for the C++ standard library as well. OS X doesn't support an equivalent of `\MT`, so this will pretty much always be present.

So why does this matter? Well, if you use this .dylib as-is to build OpenRCT2 and run the same otool call on the compiled binary, you'll get something like this:

```
OpenRCT2:
    ...
    /some/prefix/here/lib/libSomething.2.0.0.dylib (compatibility version 5.0.0, current version 5.0.0)
    ...
```

This means that when the game launches, it will look for that library at EXACTLY that path. Since we cannot expect users to have this library in this exact location, it will cause the game to fail to load. Similarly, the library itself has user dependencies that won't exist on the user's system at that exact path, and will cause the game to crash. When we distribute the game, this libraries are located in the `@rpath` directory. The rpath is hard to explain, but in our case, it refers to the `Frameworks` folder in the app bundle. This means that both the `id` and any `user dependencies` need to be edited to refer to the files being in the `@rpath` directory.

First, remove any symlinks and remove the version number from the .dylib. This is to match the other libraries already in the orctlibs bundle. Then, you need to edit the paths using `install_name_tool`. For the example I gave, you would need to call `install_name_tool -id @rpath/libSomething.dylib libSomething.dylib; install_name_tool -change /usr/local/opt/otherthing/lib/libOther.6.dylib @rpath/libOther.dylib libSomething.dylib`. If you call otool again, then you should see something like this:

```
libSomething.dylib:
    @rpath/libSomething.dylib (compatibility version 5.0.0, current version 5.0.0)
    @rpath/libOther.dylib (compatibility version 19.0.0, current version 19.3.0)
    /usr/lib/libThing.2.dylib (compatibility version 7.0.0, current version 7.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Since all the libraries referenced are now either a system dependency or have been switched to use @rpath, everything should work correctly.

This turned out to be longer than I expected. Let me know if you have any questions, and feel free to ping me on Gitter if you have trouble doing this for some library in the future.

**Comment by janisozaur** [comment]
That's quite informative.

I have one more mystery to solve for you. When #17 got merged, the builds suddenly stopped working, even though the main project itself was not updated to use any of the new files and the files already in zip were intact (I verified their checksums). Why?

**Comment by LRFLEW** [comment]
The problem was that if the libs hadn't been downloaded before (such as the case always is with Travis), then it will download the latest version, and then check the hash. If it doesn't match, then it immediately fails. I could try to edit the script such that it doesn't happen, but it _is_ a good way of knowing that the hash needs to be updated in the Xcode project. Since the hash was never edited in the develop branch, the whole branch failed.

**Comment by janisozaur** [comment]
No, I mean even after I've updated hash in the project and it linked successfully (without any of new `dylib`s). There is a step at the end of job to generate `g2.dat` which launches `openrct2` and it failed to even load. See https://github.com/OpenRCT2/OpenRCT2/pull/3699#issuecomment-220828776

**Pull request closed without merging**
