### PR TITLE
Add OpenSSL 1.0.2h for OS X

### PR DESCRIPTION
**Pull request by YJSoft**

### CODE REVIEW

**Comment by LRFLEW** [comment]
Can you guys PLEASE contact me before you merge this sort of thing. There's a lot wrong here. The id is broken, causing the app to look for the library in the wrong place, the Xcode project was never updated for it (EDIT: on the develop branch), and the compatibility version was never set. I'll work on fixing this, but you may want to roll this back for now.

**Comment by LRFLEW** [comment]
Actually, I vote to roll this back completely and use the OS's version of libcrypto instead. I'll post more in the other PR about it.

**Comment by janisozaur** [comment]
I have to agree with @LRFLEW on this one, merging libs should undergo more scrutiny and be reviewed by more people.

Especially as @YJSoft raised concerns about this possibly not really working in the first place: https://github.com/OpenRCT2/OpenRCT2/pull/3699#issuecomment-220828776

I'm sorry @YJSoft, we value your contributions, but will have to back this one out and work harder on getting it fixed.

@LRFLEW when you create a PR, can you post a technical description of what you found amiss?

For reference, see discussion in https://github.com/OpenRCT2/OpenRCT2/pull/3699 (the PR that prompted inclusion of openssl) and https://github.com/janisozaur/OpenRCT2/pull/6 (the PR that updates main OpenRCT2 repository to use these new libs)

**Comment by janisozaur** [comment]
To keep this repository size down, I suggest we remove this commit and restore f28a1a191bdba6bcee20c504cf15bec150fe0ba3 instead of reverting.

**Comment by janisozaur** [comment]
With @IntelOrca's approval, I have restored `master` to `f28a1a1`.

Overall, openssl proves to be more difficult than other libs to get done right on OS X for various reasons.

**Pull request merged**
