### PR TITLE
Added orctlibs-mac.zip

### PR DESCRIPTION
**Pull request by LRFLEW**
This is needed for OpenRCT2/OpenRCT2#2518

### CODE REVIEW

**Comment by LinusU** [comment]
What are the changes compared to the original?

**Comment by pizza2004** [comment]
@LinusU All this does is add a zip file containing libraries needed for compilation and runtime of the OS X version of the game.

**Comment by LinusU** [comment]
@pizza2004 Yes, I understand that. But I wanted to know in what way this differs from the normal `orctlibs.zip` which worked just fine for me on OS X.

@LRFLEW what changes is made in this compared to the standard `orctlibs.zip`?

**Comment by IntelOrca** [comment]
orctlibs.zip contains static libraries for Windows builds.
orctlibs-osx.zip contains OSX frameworks for native OSX .app builds.

**Comment by LRFLEW** [comment]
Well, technically I ended up going with dynamic libraries. There were some difficulties getting Frameworks to work nicely with the existing code, so I went with what worked best. (static libraries are surprisingly difficult to get to work in Xcode)

**Comment by LinusU** [comment]
Hmm, I thought that `orctlibs.zip` just contained source code, nothing compiled. I've been using that one to build under OS X and it worked fine. I was just curious why that didn't cut it...

**Comment by IntelOrca** [comment]
@LinusU It does, but it really shouldn't. It was originally intended to have pre-compiled curl and openssl as they are complicated to build. Other libraries like jansson should have also been pre-built but were not and are just in source code form.

Headers are always present as they are needed for OpenRCT2 to compile.

**Comment by LRFLEW** [comment]
> I've been using that one to build under OS X and it worked fine.

@LinusU Yes, that will always work fine, **_if**_ you have the dependencies downloaded and installed (ex. via Brew). The problem with Xcode is that it's very hard to set it up in a system-independent way to reference user installed system-libraries. The solution is to have Xcode download the built libraries itself, hence the new zip file.

**Comment by LinusU** [comment]
That clears it up, thank you!

**Pull request merged**
